export const Amazonprodcts =  [
    {
        id: 1,
        title:'samsung',
        img:'https://m.media-amazon.com/images/I/81L9f1n4pGL._AC_UL480_FMwebp_QL65_.jpg',
        price:589 ,
        max_price:899,
        rating: 4,
        quantity:1,
        category: 'grocery',
        brand:'samsung',
    },    {
        id: 2,
        title:'nokia',
        img:'https://m.media-amazon.com/images/I/81L9f1n4pGL._AC_UL480_FMwebp_QL65_.jpg',
        price:589 ,
        max_price:899,
        rating: 4,
        quantity:1,
        category: 'fashion',
        brand:'nokia',
    },    {
        id: 3,
        title:'motorolla 192 L 2 Star Direct Cool Single Door Refrigerator (RR19A241BGS/NL, Grey Silver)',
        img:'https://m.media-amazon.com/images/I/81L9f1n4pGL._AC_UL480_FMwebp_QL65_.jpg',
        price:589 ,
        max_price:899,
        rating: 4,
        quantity:1,
        category: 'appliances',
        brand:'motorolla',
    },
    {
        id: 10,
        title:'motorolla 192 L 2 Star Direct Cool Single Door Refrigerator (RR19A241BGS/NL, Grey Silver)',
        img:'https://m.media-amazon.com/images/I/81L9f1n4pGL._AC_UL480_FMwebp_QL65_.jpg',
        price:589 ,
        max_price:899,
        rating: 4,
        quantity:1,
        category: 'appliances',
        brand:'motorolla',
    },

    {
        id: 4,
        title:'apple 192 L 2 Star Direct Cool Single Door Refrigerator (RR19A241BGS/NL, Grey Silver)',
        img:'https://m.media-amazon.com/images/I/81L9f1n4pGL._AC_UL480_FMwebp_QL65_.jpg',
        price:589 ,
        max_price:899,
        rating: 4,
        quantity:1,
        category: 'beautyandmore',
        brand:'apple',
    },
    {
        id: 5,
        title:'samsung',
        img:'https://m.media-amazon.com/images/I/81L9f1n4pGL._AC_UL480_FMwebp_QL65_.jpg',
        price:589 ,
        max_price:899,
        rating: 4,
        quantity:1,
        category: 'grocery',
        brand:'samsung',
    },    {
        id: 6,
        title:'nokia',
        img:'https://m.media-amazon.com/images/I/81L9f1n4pGL._AC_UL480_FMwebp_QL65_.jpg',
        price:589 ,
        max_price:899,
        rating: 4,
        quantity:1,
        category: 'homeitem',
        brand:'nokia',
    },    {
        id: 7,
        title:'motorolla 192 L 2 Star Direct Cool Single Door Refrigerator (RR19A241BGS/NL, Grey Silver)',
        img:'https://m.media-amazon.com/images/I/81L9f1n4pGL._AC_UL480_FMwebp_QL65_.jpg',
        price:589 ,
        max_price:899,
        rating: 4,
        quantity:1,
        category: 'travel',
        brand:'motorolla',
    },

    {
        id: 8,
        title:'apple 192 L 2 Star Direct Cool Single Door Refrigerator (RR19A241BGS/NL, Grey Silver)',
        img:'https://m.media-amazon.com/images/I/81L9f1n4pGL._AC_UL480_FMwebp_QL65_.jpg',
        price:589 ,
        max_price:899,
        rating: 4,
        quantity:1,
        category: 'travel',
        brand:'apple',
    },

]